### ISSUE TITLE
Crash on missing parameter.

### ISSUE THREAD

**Issue by StephanGocht** [LeroyChew/rParSort#2]
When the code is run without output file, p.a., `./parity 10 5`, it crashes (I guess the CNF file is not initialized by default).

**Comment by LeroyChew** [comment]
`./parity 10 5` runs correctly on my end, so I can only imagine something is causing it to behave differently on different compilers.

**Comment by StephanGocht** [comment]
https://github.com/LeroyChew/rParSort/blob/3bc34151ae4bd7908e02a064069f9d52ec1daa16/Parity.cpp#L1413

I think the file open fails because cnf_name is not initialized and then the next line crashes.

**Comment by LeroyChew** [comment]
I've added an if statement to prevent this, it still runs on my end, can you let me know if this fixes this on yours?

**Comment by StephanGocht** [comment]
Yes, seems to be working now thanks.
